# Generated by Django 3.1 on 2022-05-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgalary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGalary',
            new_name='ProductGallery',
        ),
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
